### ISSUE TITLE
Test time

### ISSUE THREAD

**Issue by NoviceCrom** [HongguangZhang/DMPHN-cvpr19-master#5]
In the test stage,I found the average time to process a 720P image is about 0.91.But the dissertation says 30ms in the 1-2-4-8 model.Wonder why?

**Comment by andycor** [comment]
30ms may refer to network processing time, excluding picture reading and writing time

**Comment by HongguangZhang** [comment]
andycor is right. The reported runtime only consider the network processing time. The image reading and writing time are excluded.
